# FROZEN REFERENCE — not executed.
# Origin: agent-constitution skills/ai-router @ 9b2be20 (2026-07-01).
# See docs/legacy/README.md.
"""
configure.py — interactive router configuration wizard.

Run with:
    python configure.py
or (if installed via install.sh):
    router configure

The wizard asks:
  1. Planning-model priority — ordered list of model names for the "planning" role.
  2. Acting-model priority  — ordered list of model names for the "acting" role.

It then:
  - Writes the choice to a roles.yaml config file (default: ~/.config/ai-router/roles.yaml,
    or AIROUTER_ROLES_FILE env var override).
  - Prints a Cline settings snippet showing how to point each role at the right endpoint:
      Plan model  = subscription CLI (Claude Code / Gemini CLI) — NOT the proxy.
      Act model   = the router proxy  (http://localhost:8787/v1).

IMPORTANT: This file is GENERIC — no personal model choices are hard-coded here.
           Personal defaults live in the vault config.py only.

This script is intentionally separate from install.sh (which stays zero-touch).
install.sh prints a reminder: "run `router configure` to pick your model priorities."
"""

from __future__ import annotations

import os
import sys
from pathlib import Path
from typing import Any

# ── Available model names (mirrors ModelType enum values) ──────────────────────
KNOWN_MODELS: list[str] = [
    "claude-opus-4-8",
    "claude-sonnet-4-6",
    "claude-haiku-4-5",
    "deepseek-v4-pro",
    "deepseek-v4-flash",
    "MiniMax-M3",
    "grok-3",           # VERIFY: check https://docs.x.ai/docs for current ID
    "gpt-4.1",          # VERIFY: check https://platform.openai.com/docs/models
]

MODEL_ALIASES: dict[str, str] = {
    "opus":    "claude-opus-4-8",
    "sonnet":  "claude-sonnet-4-6",
    "haiku":   "claude-haiku-4-5",
    "deepseek-pro":   "deepseek-v4-pro",
    "deepseek-flash": "deepseek-v4-flash",
    "deepseek":       "deepseek-v4-pro",
    "minimax": "MiniMax-M3",
    "grok":    "grok-3",
    "openai":  "gpt-4.1",
    "gpt":     "gpt-4.1",
}

PROXY_BASE_URL = "http://localhost:8787/v1"

# ── Helpers ────────────────────────────────────────────────────────────────────


def _resolve(raw: str) -> str:
    """Resolve alias or strip whitespace; return canonical model name."""
    stripped = raw.strip().lower()
    return MODEL_ALIASES.get(stripped, raw.strip())


def _prompt_model_list(role: str) -> list[str]:
    """Interactive prompt: ask for an ordered list of models for `role`."""
    print(f"\n  {role.upper()} role — enter models in priority order.")
    print("  Available (aliases work too, e.g. 'opus', 'deepseek', 'grok'):")
    for m in KNOWN_MODELS:
        print(f"    {m}")
    print()
    print("  Enter one model per line. Press ENTER on an empty line when done.")

    models: list[str] = []
    idx = 1
    while True:
        raw = input(f"    [{idx}] ").strip()
        if not raw:
            if not models:
                print("  (at least one model is required)")
                continue
            break
        resolved = _resolve(raw)
        models.append(resolved)
        idx += 1

    return models


def _roles_file_path() -> Path:
    """Return the path where roles.yaml will be written."""
    env_override = os.environ.get("AIROUTER_ROLES_FILE")
    if env_override:
        return Path(env_override).expanduser()
    xdg = os.environ.get("XDG_CONFIG_HOME")
    base = Path(xdg).expanduser() if xdg else Path.home() / ".config"
    return base / "ai-router" / "roles.yaml"


def _write_roles_yaml(planning: list[str], acting: list[str], dest: Path) -> None:
    """Write a simple YAML file (stdlib only — no PyYAML dependency)."""
    dest.parent.mkdir(parents=True, exist_ok=True)
    lines = [
        "# AI Router — role priorities",
        "# Generated by `router configure`. Edit freely.",
        "# Consumed by ai_router.py when AIROUTER_ROLES_FILE points here.",
        "roles:",
        "  planning:",
    ]
    for m in planning:
        lines.append(f"    - {m}")
    lines.append("  acting:")
    for m in acting:
        lines.append(f"    - {m}")
    dest.write_text("\n".join(lines) + "\n", encoding="utf-8")


def _print_cline_snippet(planning: list[str], acting: list[str]) -> None:
    """Print a Cline/Roo-Code settings JSON snippet."""
    plan_label = planning[0] if planning else "<your-plan-model>"
    act_url    = PROXY_BASE_URL

    print("""
┌─────────────────────────────────────────────────────────────────┐
│  Cline / Roo-Code settings snippet                              │
│                                                                 │
│  Plan mode  → subscription CLI (Claude Code or Gemini CLI).     │
│              These are NOT HTTP APIs — do NOT point them at     │
│              the proxy. Configure them in Cline as the          │
│              "Claude Code" or "Gemini CLI" provider.            │
│                                                                 │
│  Act mode   → the router proxy (OpenAI-compatible endpoint).    │
│              Any provider with an API key goes here.            │
└─────────────────────────────────────────────────────────────────┘
""")
    print("  In Cline → Settings → Plan/Act models:\n")
    print(f'    Plan model : (subscription CLI — e.g. Claude Code provider)')
    print(f'    Plan note  : first choice = {plan_label}')
    print()
    print(f'    Act model  : OpenAI Compatible')
    print(f'    Act base   : {act_url}')
    print(f'    Act model  : (leave blank — router picks based on roles.yaml)')
    print()
    print("  Acting-role priority:")
    for i, m in enumerate(acting, 1):
        print(f"    {i}. {m}")
    print()
    print("  Note: start the proxy first:  uvicorn server:app --port 8787")


# ── Entry point ────────────────────────────────────────────────────────────────


def main(argv: list[str] | None = None) -> int:
    """Interactive wizard — called by `router configure`."""
    print("=" * 65)
    print("  AI Router — configuration wizard")
    print("=" * 65)
    print("""
  This wizard configures ROLE-BASED model routing.

  IMPORTANT: Plan-mode = subscription CLIs (Claude Code, Gemini CLI).
  They are NOT HTTP APIs — the router proxy cannot wrap them.
  Configure them directly in Cline as the matching CLI provider.

  Act-mode  = API providers routed through this proxy.
""")

    try:
        planning = _prompt_model_list("planning")
        acting   = _prompt_model_list("acting")
    except (KeyboardInterrupt, EOFError):
        print("\n\nAborted.")
        return 1

    dest = _roles_file_path()
    _write_roles_yaml(planning, acting, dest)
    print(f"\n  Saved → {dest}")

    _print_cline_snippet(planning, acting)
    return 0


if __name__ == "__main__":
    sys.exit(main())
